server:
  port: 8081

spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inventory_db
    username: root
    password: 06042002
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

message: Inventory Service Configuration


